version: 0.2

env:
  parameter-store:
    "GITHUB_KEY": "/CodeBuild/Github-SSH-Key"
    "GITHUB_HOST_KEY": "/CodeBuild/Github-Host-Key"
    "GITHUB_API_TOKEN": "/CodeBuild/GitHub/AccessToken"
secrets-manager:
    CLIENT_CERT_ENCODED: /CodeBuild/Certs/BBC_Production_Services_Client:Certificate
    CLIENT_KEY_ENCODED: /CodeBuild/Certs/BBC_Production_Services_Client:PrivateKey
    CA_CERT_ENCODED: /CodeBuild/Certs/Cloud_Services_Root_Trust:Certificate

phases:
  install:
    commands:
      - export CLIENT_CERT=$(echo "$CLIENT_CERT_ENCODED" | base64 --decode)
      - export CLIENT_KEY=$(echo "$CLIENT_KEY_ENCODED" | base64 --decode)
      - export CA_CERT=$(echo "$CA_CERT_ENCODED" | base64 --decode)
      - configure_github
      - configure_certs
      - load_node
      - export CLIENT_CERT=/root/client.pem
      - export CA_CERT=/root/ca.pem
      - npm install
  build:
    commands:
      - npm test
      - git submodule update --init --recursive
      - npm run release
