version: 0.2

env:
  parameter-store:
    "GITHUB_KEY": "/CodeBuild/Github-SSH-Key"
    "GITHUB_HOST_KEY": "/CodeBuild/Github-Host-Key"
    "GITHUB_API_TOKEN": "/CodeBuild/GitHub/AccessToken"
    "CLIENT_CERT": "/CodeBuild/BBC-Client-Cert"
    "CLIENT_KEY": "/CodeBuild/BBC-Client-Key"
    "CA_CERT": "/CodeBuild/BBC-CA-Cert"

phases:
  install:
    commands:
      - configure_github
      - configure_certs
      - load_node
      - export CLIENT_CERT=/root/client.pem
      - export CA_CERT=/root/ca.pem
      - npm install
  build:
    commands:
      - npm test
      - git submodule update --init --recursive
      - npm run release
